version: '2'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        STATIC_URL: 'http://localhost'
        DATA_VERSION_REF: '2017.12.with.FT'
    restart: unless-stopped
    links:
      - api
    ports:
      - 80:80
  api:
    build:
      dockerfile: Dockerfile
      context: api
      args:
        DATA_VERSION_REF: '2017.12.with.FT'
    restart: unless-stopped
    environment:
      - SECRET_KEY=dev_secret
      - DEBUG=True
    ports:
      - 8000:8000
